---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: ljfranklin/terraform-resource
    tag: dev

inputs:
  - name: resource-src
  - name: terraform-release
    optional: true
  - name: terragrunt-release
    optional: true

outputs:
  - name: build-artifacts

run:
  path: resource-src/ci/tasks/build-multiarch-artifacts

params:
  DOCKERFILE_DIR: "resource-src/docker-prod/"
  TERRAGRUNT_RELEASE_DIR: "terragrunt-release"
  TERRAFORM_RELEASE_DIR: "terraform-release"
