#!/bin/bash

set -eu -o pipefail

release_dir="$( cd "$( dirname "$0" )" && cd ../.. && pwd )"
workspace_dir="$( cd "${release_dir}" && cd .. && pwd )"

# env
: ${DOCKERFILE_DIR:?}
: ${TARGETARCH:=amd64}

if [ -f "${workspace_dir}/${TERRAFORM_RELEASE_DIR}/tag" ]; then
  terraform_version="$( cat "${workspace_dir}/${TERRAFORM_RELEASE_DIR}/tag" )"
  terraform_version="${terraform_version:1}" # Trim trailing v from tag
else
  terraform_version="$( cat "${release_dir}/config/terraform-version" )"
fi

# outputs
if [ "$#" -eq 1 ]; then
  output_dir="$1"
else
  output_dir="${workspace_dir}/build-artifacts"
fi
mkdir -p "${output_dir}/terraform"

tmp_dir="$(mktemp -d /tmp/build-artifacts-XXXXXX)"
trap "{ rm -rf "${tmp_dir}" ; }" EXIT

pushd "${tmp_dir}" > /dev/null
  echo "Downloading artifacts..."
  wget -O opentofu_${terraform_version}_linux_${TARGETARCH}.zip https://github.com/opentofu/opentofu/releases/download/v${terraform_version}/tofu_${terraform_version}_linux_amd64.zip
  unzip opentofu_${terraform_version}_linux_${TARGETARCH}.zip -d "${output_dir}/terraform"

popd > /dev/null

echo "Building resource..."
pushd "${release_dir}" > /dev/null
  GOARCH="${TARGETARCH}" ./scripts/build "${output_dir}"
popd > /dev/null

cp "${workspace_dir}/${DOCKERFILE_DIR}/Dockerfile" "${output_dir}/"

if [ -f "${workspace_dir}/${TERRAGRUNT_RELEASE_DIR}/terragrunt_linux_${TARGETARCH}" ]; then
  cp ${workspace_dir}/${TERRAGRUNT_RELEASE_DIR}/terragrunt_linux_${TARGETARCH} ${output_dir}/terraform/terragrunt
  chmod +x ${output_dir}/terraform/terragrunt
fi

echo "Successfully fetched all Terraform artifacts!"
